version: "3.0"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
      
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
